# Generated by Django 6.0 on 2026-01-09 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='user_id',
        ),
        migrations.AddField(
            model_name='user',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AddField(
            model_name='user',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='student_name',
            field=models.CharField(default='noname', max_length=30),
        ),
        migrations.AddField(
            model_name='user',
            name='verification_string',
            field=models.CharField(default=823165873, max_length=255, unique=True),
            preserve_default=False,
        ),
    ]
